var arr = ["alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo", "alobalohalo"]

var result = arr.forEach(function(item) {
    item += "bun";
})
var result = [];
for (var i in arr) {
    result.push(arr[i] += "bun");
}
